services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    stop_grace_period: 30s # allow enough time to shut down the various services
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "512mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb # Passes the USB Coral, needs to be modified for other versions
      - /dev/apex_0:/dev/apex_0 # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11 # For Raspberry Pi 4B
      - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yaml:/config/config.yaml
      - ./storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "5000:5000" # Internal unauthenticated access. Expose carefully.
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    network_mode: host
    environment:
      FRIGATE_RTSP_USER1: ${CAM1_USER}
      FRIGATE_RTSP_PASSWORD1: ${CAM1_PASS}
      FRIGATE_RTSP_HOST1: ${CAM1_HOST}

      FRIGATE_RTSP_USER2: ${CAM2_USER}
      FRIGATE_RTSP_PASSWORD2: ${CAM2_PASS}
      FRIGATE_RTSP_HOST2: ${CAM2_HOST}

      FRIGATE_RTSP_USER3: ${CAM3_USER}
      FRIGATE_RTSP_PASSWORD3: ${CAM3_PASS}
      FRIGATE_RTSP_HOST3: ${CAM3_HOST}
volumes:
  storage: