mqtt:
  enabled: true
  host: "{{ MQTT_HOST }}"
  user: "{{ MQTT_USER }}"
  port: 1883
  password: "{{ MQTT_PASSWORD }}"
  topic_prefix: "{{ MQTT_TOPIC_PREFIX }}"

detectors:
  cpu1:
    type: cpu

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1

snapshots:
  enabled: True
  bounding_box: true
  retain:
    default: 1

cameras:
  CAMERA_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER1}:{FRIGATE_RTSP_PASSWORD1}@{FRIGATE_RTSP_HOST1}/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

  CAMERA_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER2}:{FRIGATE_RTSP_PASSWORD2}@{FRIGATE_RTSP_HOST2}/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

  CAMERA_3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER3}:{FRIGATE_RTSP_PASSWORD3}@{FRIGATE_RTSP_HOST3}/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

version: 0.15-1
