mqtt:
  enabled: true
  host: 172.30.10.2 
  user: "mqtt_user"
  port: 1883
  password: "mqtt2025*"
  topic_prefix: frigate/events

detectors:
  cpu1:
    type: cpu
    
record:
  enabled: True
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1

snapshots:
  enabled: True
  bounding_box: true
  retain:
    default: 1

cameras:
  CAMERA_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:m0t0rSr4d@172.30.3.89:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

  CAMERA_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:m0t0rSr4d@172.30.3.90:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car
  
  CAMERA_3:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://admin:m0t0rSr4d@172.30.3.78:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

version: 0.15-1

