mqtt:
  enabled: true
  host: ${FRIGATE_MQTT_HOST}
  user: ${FRIGATE_MQTT_USER}
  password: ${FRIGATE_MQTT_PASSWORD}
  port: 1883
  topic_prefix: ${FRIGATE_MQTT_TOPIC_PREFIX}
  client_id: "frigate01"

detectors:
  cpu1:
    type: cpu

record:
  enabled: True
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 1
  detections:
    retain:
      days: 1

snapshots:
  enabled: True
  bounding_box: true
  retain:
    default: 1

cameras:
  CAMERA_1:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${FRIGATE_CAM1_USER}:${FRIGATE_CAM1_PASS}@${FRIGATE_CAM1_HOST}/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

  CAMERA_2:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://${FRIGATE_CAM2_USER}:${FRIGATE_CAM2_PASS}@${FRIGATE_CAM2_HOST}/cam/realmonitor?channel=1&subtype=0
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
    objects:
      track:
        - person
        - dog
        - cat
        - car

version: 0.15-1
